"""baseline: schema atual (equivalente a create_all + migrations ad-hoc)

Revision ID: fc9067718964
Revises: 
Create Date: 2026-08-23 16:01:58.980493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9067718964'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('erro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes',
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('email_contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_familias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo_original', sa.String(), nullable=False),
    sa.Column('familia_original', sa.String(), nullable=False),
    sa.Column('grupo_normalizado', sa.String(), nullable=False),
    sa.Column('familia_normalizada', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupos_familias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_familias_familia_original'), ['familia_original'], unique=False)
        batch_op.create_index(batch_op.f('ix_grupos_familias_grupo_original'), ['grupo_original'], unique=False)

    op.create_table('produtos',
    sa.Column('codigo_chamada', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('familia', sa.String(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_chamada')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_familia'), ['familia'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_grupo'), ['grupo'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('produtos_count', sa.Integer(), nullable=True),
    sa.Column('codigos_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_job_id'), ['job_id'], unique=True)

    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tentativas_login_username'), ['username'], unique=False)

    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_user_id'), ['user_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nome_exibicao', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('whatsapp_contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_precos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_chamada', sa.String(), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('markup', sa.Float(), nullable=False),
    sa.Column('margem', sa.Float(), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('sync_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_chamada'], ['produtos.codigo_chamada'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_precos_codigo_chamada'), ['codigo_chamada'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_precos_data_coleta'), ['data_coleta'], unique=False)

    op.create_table('produto_codigos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('codigo_chamada', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_chamada'], ['produtos.codigo_chamada'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto_codigos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_codigos_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_codigos_codigo_chamada'), ['codigo_chamada'], unique=False)

    op.create_table('sessoes_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('codigo_convite', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('encerrado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_convite')
    )
    with op.batch_alter_table('sessoes_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_inventario_status'), ['status'], unique=False)

    op.create_table('itens_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('familia', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_inventario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sessao_id', 'usuario_id', 'codigo', name='uq_sessao_usuario_codigo')
    )
    with op.batch_alter_table('itens_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_inventario_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_inventario_sessao_id'), ['sessao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_inventario_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_inventario_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_itens_inventario_sessao_id'))
        batch_op.drop_index(batch_op.f('ix_itens_inventario_codigo'))

    op.drop_table('itens_inventario')
    with op.batch_alter_table('sessoes_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_inventario_status'))

    op.drop_table('sessoes_inventario')
    with op.batch_alter_table('produto_codigos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_codigos_codigo_chamada'))
        batch_op.drop_index(batch_op.f('ix_produto_codigos_codigo'))

    op.drop_table('produto_codigos')
    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_precos_data_coleta'))
        batch_op.drop_index(batch_op.f('ix_historico_precos_codigo_chamada'))

    op.drop_table('historico_precos')
    op.drop_table('whatsapp_contatos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))

    op.drop_table('usuarios')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_user_id'))

    op.drop_table('token_blacklist')
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tentativas_login_username'))

    op.drop_table('tentativas_login')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_job_id'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_grupo'))
        batch_op.drop_index(batch_op.f('ix_produtos_familia'))

    op.drop_table('produtos')
    with op.batch_alter_table('grupos_familias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_familias_grupo_original'))
        batch_op.drop_index(batch_op.f('ix_grupos_familias_familia_original'))

    op.drop_table('grupos_familias')
    op.drop_table('email_contatos')
    op.drop_table('configuracoes')
    op.drop_table('cache_status')
    # ### end Alembic commands ###
