"""initial_schema

Revision ID: 97ee0238cc20
Revises: 
Create Date: 2026-05-27 08:55:12.587193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ee0238cc20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('erro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes',
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('email_contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_familias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo_original', sa.String(), nullable=False),
    sa.Column('familia_original', sa.String(), nullable=False),
    sa.Column('grupo_normalizado', sa.String(), nullable=False),
    sa.Column('familia_normalizada', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_familias_familia_original'), 'grupos_familias', ['familia_original'], unique=False)
    op.create_index(op.f('ix_grupos_familias_grupo_original'), 'grupos_familias', ['grupo_original'], unique=False)
    op.create_table('produtos',
    sa.Column('codigo_chamada', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('familia', sa.String(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_chamada')
    )
    op.create_index(op.f('ix_produtos_familia'), 'produtos', ['familia'], unique=False)
    op.create_index(op.f('ix_produtos_grupo'), 'produtos', ['grupo'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('produtos_count', sa.Integer(), nullable=True),
    sa.Column('codigos_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_job_id'), 'sync_jobs', ['job_id'], unique=True)
    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tentativas_login_username'), 'tentativas_login', ['username'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nome_exibicao', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('whatsapp_contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_precos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_chamada', sa.String(), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('markup', sa.Float(), nullable=False),
    sa.Column('margem', sa.Float(), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('sync_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_chamada'], ['produtos.codigo_chamada'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_precos_codigo_chamada'), 'historico_precos', ['codigo_chamada'], unique=False)
    op.create_index(op.f('ix_historico_precos_data_coleta'), 'historico_precos', ['data_coleta'], unique=False)
    op.create_index('idx_hp_codigo_data', 'historico_precos', ['codigo_chamada', 'data_coleta'], unique=False)
    op.create_table('produto_codigos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('codigo_chamada', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_chamada'], ['produtos.codigo_chamada'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_codigos_codigo'), 'produto_codigos', ['codigo'], unique=False)
    op.create_index(op.f('ix_produto_codigos_codigo_chamada'), 'produto_codigos', ['codigo_chamada'], unique=False)
    op.create_table('sessoes_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('codigo_convite', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('encerrado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_convite')
    )
    op.create_index(op.f('ix_sessoes_inventario_status'), 'sessoes_inventario', ['status'], unique=False)
    op.create_table('itens_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('familia', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_inventario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sessao_id', 'usuario_id', 'codigo', name='uq_sessao_usuario_codigo')
    )
    op.create_index(op.f('ix_itens_inventario_codigo'), 'itens_inventario', ['codigo'], unique=False)
    op.create_index(op.f('ix_itens_inventario_sessao_id'), 'itens_inventario', ['sessao_id'], unique=False)
    op.create_index(op.f('ix_itens_inventario_usuario_id'), 'itens_inventario', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_inventario_usuario_id'), table_name='itens_inventario')
    op.drop_index(op.f('ix_itens_inventario_sessao_id'), table_name='itens_inventario')
    op.drop_index(op.f('ix_itens_inventario_codigo'), table_name='itens_inventario')
    op.drop_table('itens_inventario')
    op.drop_index(op.f('ix_sessoes_inventario_status'), table_name='sessoes_inventario')
    op.drop_table('sessoes_inventario')
    op.drop_index(op.f('ix_produto_codigos_codigo_chamada'), table_name='produto_codigos')
    op.drop_index(op.f('ix_produto_codigos_codigo'), table_name='produto_codigos')
    op.drop_table('produto_codigos')
    op.drop_index(op.f('ix_historico_precos_data_coleta'), table_name='historico_precos')
    op.drop_index(op.f('ix_historico_precos_codigo_chamada'), table_name='historico_precos')
    op.drop_index('idx_hp_codigo_data', table_name='historico_precos')
    op.drop_table('historico_precos')
    op.drop_table('whatsapp_contatos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_tentativas_login_username'), table_name='tentativas_login')
    op.drop_table('tentativas_login')
    op.drop_index(op.f('ix_sync_jobs_job_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_grupo'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_familia'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_grupos_familias_grupo_original'), table_name='grupos_familias')
    op.drop_index(op.f('ix_grupos_familias_familia_original'), table_name='grupos_familias')
    op.drop_table('grupos_familias')
    op.drop_table('email_contatos')
    op.drop_table('configuracoes')
    op.drop_table('cache_status')
    # ### end Alembic commands ###
